### ISSUE TITLE
Game crashes during battle

### ISSUE THREAD

**Issue by SeanChengN** [justinwon777/HumanCompanions#11]
Game crash occurs during the battle with the pillager.
humancompanions-1.18.1-1.4.4
https://pastebin.com/b1x3dYp1

**Comment by CoDrie** [comment]
Same here with other error: (also version1.4.4)
Entity Type: minecraft:arrow (net.minecraft.world.entity.projectile.Arrow)
https://pastebin.com/6gbYcpww

complete server on PloudOs crashes

**Comment by turtle331** [comment]
Here is my [latest.log](https://github.com/justinwon777/HumanCompanions/files/8550134/latest.log). For me and my Friend it happend that the companion tried to kill a cow and hitted each other and started a war. A war that killed the server permanatly. If both player in that region / Chunk enter the server the server crashes. If another Player joins from a diffrent region/chunk its not a problem at all. Untill he walks / tp over to the exact location where the incident happend. The region file is not existing where the error is happening.  1.16 Version for me.

**Comment by justinwon777** [comment]
For all these, looks like the issue is when a companion gets hit by an arrow. I'm not able to reproduce it though, so having trouble fixing it. If anyone finds a way to reproduce it, let me know.

**Comment by turtle331** [comment]
if you want I still have the save file with the "bugged" chunks, you can take a deeper look into it. Not sure though how I can send it to you. Somebody on the "Life in a Village 2" modpack discord fixed the world for me by using the nbt editor to remove the arrows.

**Comment by justinwon777** [comment]
> if you want I still have the save file with the "bugged" chunks, you can take a deeper look into it. Not sure though how I can send it to you. Somebody on the "Life in a Village 2" modpack discord fixed the world for me by using the nbt editor to remove the arrows.

You can attach files here. Maybe just zip the world folder it and then attach it?

**Comment by turtle331** [comment]
![grafik](https://user-images.githubusercontent.com/24854059/164998763-e6f9c64b-a269-4f13-bfa0-3c9da429ab53.png)
I'm not sure why but I can't upload *.zip files here at the moment

**Comment by turtle331** [comment]
https://www.filemail.com/d/pcbyteyqhcdojid
Lets try it this way then

**Comment by turtle331** [comment]
If you are intrested @justinwon777 I can create a Server for the modpack Life in a Village 2 right now. I can try to get situation like it happend on the map, but I need a second player. Sadly I dont one right now though.

**Comment by turtle331** [comment]
![grafik](https://user-images.githubusercontent.com/24854059/164999048-b3085bc6-a70d-4cf0-896d-c6b4c8331750.png)
![grafik](https://user-images.githubusercontent.com/24854059/164999053-86848419-1eae-4ec8-8127-c1d7088cfc6f.png)

Here are some guide lines where it happend.

This it the modpack where the mod is used in:
https://www.curseforge.com/minecraft/modpacks/life-in-the-village-2

The version of the modpack is https://www.curseforge.com/minecraft/modpacks/life-in-the-village-2/files/3707056
(1.32)

**Comment by justinwon777** [comment]
I got the files, thanks. No need to make a server right now. I'll see what I can do.

**Comment by justinwon777** [comment]
@SeanChengN  and @AndreDriesel I'm pretty sure I fixed your issues in the latest version 1.4.6. @turtle331 your crash is happening somewhere else so I don't know yet what the problem is.
