### ISSUE TITLE
House distance config is NOT working...

### ISSUE THREAD

**Issue by bokomix** [justinwon777/HumanCompanions#17]
I really like the idea of having companions to help me out on my adventures and this mod seems really awesome for that! however I think they should be rarer... and I find their houses spawn wayyy too often for my taste, I tried using the range between house config to change that but it doesn't seem to work! :( no matter what number I put high or low, the frequency stays the same. -_-
I would aprettiate it if it would be fixed thanks! ^^  
(oh and I'd like to request an attack animation for the knights as well, I feel like it's missing)

**Comment by justinwon777** [comment]
Which mod and minecraft versions?

**Comment by bokomix** [comment]
> Which mod and minecraft versions?

Mod: Human companions
Version: 1.18.2

**Comment by justinwon777** [comment]
You have to use datapacks in 1.18.2 for structures. Config file won't work.

**Comment by bokomix** [comment]
> You have to use datapacks in 1.18.2 for structures. Config file won't work.

What datapack am I supposed to use?
Like how do I do that?

**Comment by justinwon777** [comment]
I've never made a datapack so I don't know how to help, sorry, but the things you wanna change are the spacing and separation fields here: https://github.com/justinwon777/HumanCompanions/blob/main/forge%201.18.2/src/main/resources/data/humancompanions/worldgen/structure_set/companion_house.json#L39

**Comment by bokomix** [comment]
> I've never made a datapack so I don't know how to help, sorry, but the things you wanna change are the spacing and separation fields here: https://github.com/justinwon777/HumanCompanions/blob/main/forge%201.18.2/src/main/resources/data/humancompanions/worldgen/structure_set/companion_house.json#L39

Ok thanks! ^^
