### ISSUE TITLE
Allow Human Companions to attack all Raiders, beyond vanilla Minecraft ones

### ISSUE THREAD

**Issue by Calculus-Master** [justinwon777/HumanCompanions#20]
This was brought up to my regarding my mod that adds more Raiders - the Human Companions won't attack modded Raiders. I believe this is because in CompanionData class, the targets for the Human Companion mobs are hardcoded for all vanilla Minecraft hostile creatures. 

Maybe a simple fix, would be to include the Raider.class in the array for it?

`public static Class<?>[] alertMobs = new Class<?>[]{
            Blaze.class,
            CaveSpider.class,
            Drowned.class,
            ElderGuardian.class,
            EnderMan.class,
            Endermite.class,
            Evoker.class,
            Ghast.class,
            Giant.class,
            Guardian.class,
            Hoglin.class,
            Husk.class,
            Illusioner.class,
            MagmaCube.class,
            Phantom.class,
            Pillager.class,
            Shulker.class,
            Silverfish.class,
            Skeleton.class,
            Slime.class,
            Spider.class,
            Stray.class,
            Vex.class,
            Vindicator.class,
            Witch.class,
            WitherSkeleton.class,
            Zoglin.class,
            Zombie.class,
            ZombieVillager.class,
            ZombifiedPiglin.class,
            Raider.class
    };`

**Comment by justinwon777** [comment]
Done in version 1.5.1
