### ISSUE TITLE
Remove damage downscaling for archer and arbalist 

### ISSUE THREAD

**Issue by CoronRing** [justinwon777/HumanCompanions#24]
**Proposal**
Remove damage down-scaling for archer and arbalist. Currently archer and arbalist have reduced damage and accuracy, this makes them a lot harder to use. Since archer is actual human and not a skeleton, it makes sense for him to shoot stronger and better.

**Comment by justinwon777** [comment]
Their damage isn't downscaled and the archer's accuracy depends on the difficulty, gets more inaccurate on harder difficulties. On peaceful, archer is more accurate than skeleton. On hard it's the opposite.

**Comment by justinwon777** [comment]
Also, even if you were right, considering they have unlimited arrows, I don't want to buff them and make them too good. Archer already has extended range compared to skeleton.
