### ISSUE TITLE
modpack server crash

### ISSUE THREAD

**Issue by TTripa96** [justinwon777/HumanCompanions#32]
hi i am having a server crash with human companions on a server with a modpack i created...

i dosent crash when you play single player just on the server anyhelp?

[crash-2023-01-20_22.18.45-server.txt](https://github.com/justinwon777/HumanCompanions/files/10471084/crash-2023-01-20_22.18.45-server.txt)
- Logs
Minecraft 1.16.5
Forge 1.16.5 [36.2.39]
Mod 1.16.5 v 1.7.3

**Comment by justinwon777** [comment]
Minecraft version: ?
Forge version: ?
Mod version: ?

**Comment by TTripa96** [comment]
Minecraft 1.16.5
Forge 1.16.5 [36.2.39]
Mod 1.16.5 v 1.7.2g

**Comment by justinwon777** [comment]
Should be fixed alongside this: https://github.com/justinwon777/HumanCompanions/issues/33
