### ISSUE TITLE
[1.16.5] Multipe Bugs for human companions on server

### ISSUE THREAD

**Issue by DoctorMage** [justinwon777/HumanCompanions#33]
**Describe the bug**
Interacting with a human companion sometimes will cause server to crash

World crashes upon generating human companion structure

**To Reproduce**
Load up human companions 1.6.0 on a server find a human companion interact with them and server will crash (seems to be random).

1.7.0 - 1.7.2 Create server with mod added and if structure is generated server will crash

**Versions (Please fill this out)**
Minecraft version: 1.16.5
Forge version:36.2.39
Human Companions version: 1.6.0 - 1.7.2 

**Additional info**
[crash-2023-01-28_00.18.24-server.txt](https://github.com/justinwon777/HumanCompanions/files/10527090/crash-2023-01-28_00.18.24-server.txt)

[crash-2023-01-27_23.43.20-server.txt](https://github.com/justinwon777/HumanCompanions/files/10527091/crash-2023-01-27_23.43.20-server.txt)

**Comment by justinwon777** [comment]
Did you try mod version 1.7.3?

**Comment by DoctorMage** [comment]
mistake on my end meant 1.6.0 - 1.7.3
 
 crash report regarding world gen with just  human companions 1.7.3
[crash-2023-01-27_23.43.20-server(1).txt](https://github.com/justinwon777/HumanCompanions/files/10531067/crash-2023-01-27_23.43.20-server.1.txt)
