### ISSUE TITLE
My night had babies? Their food request is Null Null Null Null

### ISSUE THREAD

**Issue by Jetpack-Cat** [justinwon777/HumanCompanions#36]
**Describe the bug**
I was giving a summoned companion food, he became my companion. I kept right clicking him with food and he had 2 little baby companions appear. When right clicking them with an empty hand it said they wanted Null Null Null Null

**To Reproduce**
Do what I did above

**Versions (Please fill this out)**
Minecraft version: 1.16.5
Forge version: 36.2.39
Human Companions version: humancompanions-1.16.5-1.7.3-fix.jar

**Additional info**
Add anything that would help figure out the issue, such as...

![2023-02-25_16 02 59](https://user-images.githubusercontent.com/100042170/221385200-bdb6443c-6774-4856-a35d-9556ec2f7415.png)

[latest.log](https://github.com/justinwon777/HumanCompanions/files/10832569/latest.log)

**Comment by justinwon777** [comment]
They don't work and are useless, so you can leave them alone or kill them
