### ISSUE TITLE
Crash on encountering companions for the first time

### ISSUE THREAD

**Issue by DraconicArcher** [justinwon777/HumanCompanions#51]
**Describe the bug**
I teleported to an area after installing the mod and the game crashed. It crashed again on every reload until I removed the mod.

**To Reproduce**
I'm not sure? /locate structure for a house you haven't been to before and tp there?

**Versions (Please fill this out)**
Minecraft version: 1.20.1
Forge version: 47.3.0
Human Companions version: 1.7.5
[crash-2024-11-13_22.24.06-client.txt](https://github.com/user-attachments/files/17742676/crash-2024-11-13_22.24.06-client.txt)

**Additional info**
Add anything that would help figure out the issue, such as...
- Screenshots
- Videos
- Logs

**Comment by justinwon777** [comment]
Fixed in 1.7.6
